"""
Yelp – Coffee Shop Search (Python Wrapper)
Search: "best coffee shops" in "Portland, OR"
Sort by: Highest Rated
Extract up to 5 results with name, rating, reviews, price range.

This script calls the JavaScript/Stagehand version (yelp_search.js) which uses
Stagehand's anti-detection browser to bypass DataDome CAPTCHA.

Note: yelp_search.py is auto-generated by the JS script and will be overwritten.
Use this wrapper (run_yelp_search.py) for Python access.
"""

import json
import os
import re
import subprocess
import sys


def run(
    search_term: str = "best coffee shops",
    location: str = "Portland, OR",
    max_results: int = 5,
) -> list:
    """
    Run Yelp search using Stagehand (via Node.js subprocess).
    Returns list of coffee shop dicts with name, rating, reviews, price_range.
    """
    print("=" * 59)
    print("  Yelp – Coffee Shop Search (via Stagehand)")
    print("=" * 59)
    print(f'  Search: "{search_term}" in "{location}"')
    print(f"  Sort by: Highest Rated")
    print(f"  Extract up to {max_results} results\n")

    # Get path to JS script (same directory)
    script_dir = os.path.dirname(os.path.abspath(__file__))
    js_script = os.path.join(script_dir, "yelp_search.js")

    if not os.path.exists(js_script):
        print(f"ERROR: {js_script} not found")
        return []

    print(f"🚀 Running Stagehand: node {os.path.basename(js_script)}\n")

    try:
        # Run the JS script via Node.js (use utf-8 encoding)
        result = subprocess.run(
            ["node", js_script],
            cwd=script_dir,
            capture_output=True,
            timeout=180,  # 3 minute timeout
            encoding="utf-8",
            errors="replace",  # Replace undecodable chars
        )

        # Print JS output (for visibility)
        if result.stdout:
            print(result.stdout)
        if result.stderr:
            print(result.stderr, file=sys.stderr)

        if result.returncode != 0:
            print(f"ERROR: Node process exited with code {result.returncode}")
            return []

        # Parse results from output
        # Format: "  1. Name\n     Rating:  4.5\n     Reviews: 123\n     Price:   $$"
        results = []
        output = result.stdout or ""
        lines = output.split("\n")
        i = 0
        while i < len(lines) and len(results) < max_results:
            line = lines[i].strip()
            # Match "  1. Shop Name" pattern
            match = re.match(r"^\d+\.\s+(.+)$", line)
            if match:
                shop = {
                    "name": match.group(1).strip(),
                    "rating": "N/A",
                    "reviews": "N/A",
                    "price_range": "N/A",
                }
                # Look ahead for Rating, Reviews, Price lines
                for j in range(i + 1, min(i + 5, len(lines))):
                    detail = lines[j].strip()
                    if detail.startswith("Rating:"):
                        shop["rating"] = detail.split(":", 1)[1].strip()
                    elif detail.startswith("Reviews:"):
                        shop["reviews"] = detail.split(":", 1)[1].strip()
                    elif detail.startswith("Price:"):
                        shop["price_range"] = detail.split(":", 1)[1].strip()
                results.append(shop)
            i += 1

        print(f"\n✅ Parsed {len(results)} results from Stagehand output")
        return results

    except subprocess.TimeoutExpired:
        print("ERROR: Stagehand script timed out")
        return []
    except FileNotFoundError:
        print("ERROR: Node.js not found. Please install Node.js.")
        return []
    except Exception as e:
        print(f"ERROR: {e}")
        return []


if __name__ == "__main__":
    items = run()
    print(f"\nTotal results: {len(items)}")
    if items:
        print("\nParsed data:")
        print(json.dumps(items, indent=2))
